controller_list:
  - name: ur5_manipulator_controller #arm_controller for simulation ur5_manipulator_controller for upload
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
